import Head from "next/head";
import React from "react";

export interface AboutProps {}

const About: React.SFC<AboutProps> = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>About</div>
    </>
  );
};

export default About;
